### ISSUE TITLE
Sourcemaps?

### ISSUE THREAD

**Issue by parmactep** [kobezzza/Monic#2]
А как насчет поддержки sourcemap`ов? Не планируется ли случайно?

**Comment by parmactep** [comment]
Теоретически не должно быть сложностей...

**Comment by kobezzza** [comment]
Я сделаю это, ориентировачно в течении этого месяца.

**Comment by parmactep** [comment]
Не срослось?

**Comment by kobezzza** [comment]
> Не срослось

К сожалению завал на работе произошел, не смог время выделить :(
Буду стараться сделать при первой возможности.

**Comment by kobezzza** [comment]
Сделано https://github.com/MonicBuilder/Monic
